// Note 
// - Các thư viện cần install:
//     1. react-html-table-to-excel để xuất file excel từ html dom 
//     (import ReactToExcel from 'react-html-table-to-excel' )
//     2. jquery để sử dụng jquery
//     ( import $, {event} from 'jquery')
//     3. axios để kết nối với backend
//     (import axios from 'axios')
//     4. react-router-dom để tạo componentTree, gán đường dẫn url
//     (import {BrowserRouter as Router, Route, Switch} from 'react-router-dom';)
//     5. react-redux để sử dụng thư viện redux
//     ( import {connect} from 'react-redux';)
